#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Convert a WAV greeting clip into app/kws/greeting_pcm.c (16 kHz mono int16
# PCM embedded in flash), played by "kws wake" as the offline voice reply.
#
# Standard-library only (wave + audioop) — no ffmpeg needed.  (For m4a/mp3,
# first decode to WAV, e.g. with gst-launch-1.0 ... ! wavenc ! filesink.)
#
# Usage:
#   python3 app/kws/make_greeting.py hello.wav [--slow 1.12] [--peak 24000]
#     --slow  : time-stretch factor (>1 = slower & a bit lower pitch)
#     --peak  : normalise so the loudest sample hits this |amplitude|
#               (24000 ≈ 0.73 full-scale: loud but with headroom so the
#                Class-D PA doesn't clip / distort)
#
# Processing: mono -> 16 kHz -> time-stretch -> DC removal -> peak normalise.

import sys
import wave
import audioop
import struct
import os
import argparse

APACHE = """/****************************************************************************
 * apps/examples/kws — offline voice-reply PCM (generated by make_greeting.py)
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  Licensed under the Apache License,
 * Version 2.0.  See http://www.apache.org/licenses/LICENSE-2.0
 *
 * Offline voice-reply greeting: 16 kHz mono int16 PCM, stored in flash.
 ****************************************************************************/

#include <stdint.h>

"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("wav")
    ap.add_argument("--slow", type=float, default=1.12)
    ap.add_argument("--peak", type=int, default=24000)
    ap.add_argument("--rms", type=int, default=0,
                    help="if >0, normalise by average loudness (RMS) to this "
                         "level and hard-limit peaks — much louder than "
                         "peak-normalise. Typical 7000-9000.")
    ap.add_argument("--symbol", default="greeting",
                    help="C symbol base -> g_<symbol>_pcm / g_<symbol>_pcm_len "
                         "(e.g. 'greeting' or 'retry')")
    ap.add_argument("--out", default="",
                    help="output .c path (default: <symbol>_pcm.c beside this "
                         "script)")
    args = ap.parse_args()

    w = wave.open(args.wav, "rb")
    sw, ch, fr = w.getsampwidth(), w.getnchannels(), w.getframerate()
    data = w.readframes(w.getnframes())
    w.close()

    if sw != 2:
        data = audioop.lin2lin(data, sw, 2)
    if ch == 2:
        data = audioop.tomono(data, 2, 0.5, 0.5)
    if fr != 16000:
        data, _ = audioop.ratecv(data, 2, 1, fr, 16000, None)

    # Time-stretch: emit more samples so playback at the fixed 16 kHz DAC
    # takes longer (slower tempo, slightly lower pitch).
    if args.slow and abs(args.slow - 1.0) > 1e-3:
        data, _ = audioop.ratecv(data, 2, 1, 16000, int(16000 * args.slow), None)

    samples = list(struct.unpack("<%dh" % (len(data) // 2), data))

    # DC removal (center around zero)
    mean = sum(samples) / len(samples)
    samples = [s - mean for s in samples]

    if args.rms > 0:
        # Loudness (RMS) normalise + hard limit: raises average level a lot
        cur = (sum(s * s for s in samples) / len(samples)) ** 0.5 or 1.0
        g = args.rms / cur
        mode = "rms=%d" % args.rms
    else:
        # Peak normalise (loud, with headroom)
        peak = max(1.0, max(abs(s) for s in samples))
        g = args.peak / peak
        mode = "peak=%d" % args.peak

    samples = [max(-32768, min(32767, int(round(s * g)))) for s in samples]

    out = args.out or os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                   "%s_pcm.c" % args.symbol)
    arr = "g_%s_pcm" % args.symbol
    with open(out, "w") as f:
        f.write(APACHE)
        f.write("const int16_t %s[] =\n{\n" % arr)
        for i in range(0, len(samples), 16):
            f.write("  " + ",".join("%d" % x for x in samples[i:i + 16]) + ",\n")
        f.write("};\n\n")
        f.write("const int %s_len = %d;\n" % (arr, len(samples)))

    print("wrote %s: %s, %d samples (%.2f s @16k), slow=%.2f %s"
          % (out, arr, len(samples), len(samples) / 16000.0, args.slow, mode))


if __name__ == "__main__":
    main()
